### ISSUE TITLE
Example of how to use this?

### ISSUE THREAD

**Issue by GeoffPlumbee** [jongyoul/gradle-slack-plugin#1]
Would love an example of how to use this?

**Comment by jongyoul** [comment]
Hi! Thanks for contacting me. I didn't update docs yet because I thought no one has been interested in it yet. Anyway, here is my example

```
slack {
  webhookUrl 'https://hooks.slack.com/services/TXXXXXXXX/BX/xxxxxxxx'
  message {
    text = "Project is built newly and deployed into *${deployMode.toUpperCase()}*"
    channel = '#channel-name'
    attachment {
      authorName = gitUsername
      color = 'good'
      title = "Branch: ${gitBranchName}(${gitCommitHash})"
      titleLink = "https://github.com/link/i/want/to/redirect"
      field {
        title = 'Built'
        value = 'Success'
        shortValue = true
      }
      field {
        title = 'Deployed'
        value = 'Success'
        shortValue = true
      }
    }
  }
}
```

That message structure is from current slack doc, then you can reference from https://api.slack.com/docs/messages

Hope this help, and if you have any question, feel free to talk to me

**Comment by GeoffPlumbee** [comment]
Hi thanks for responding so quickly. 
Perhaps I am still a bit new to gradle plugins, but I'm not clear on how is this invoked from build.gradle?

**Comment by jongyoul** [comment]
You could add my plugin into your build.gradle and you can that block into your build.gradle, too. To test it, you can run `./gradlew publishToSlack`

**Comment by GeoffPlumbee** [comment]
great thank you! thats working now 💃

**Comment by jongyoul** [comment]
Sounds great!! :-)
