### ISSUE TITLE
Add support for url in Element model

### ISSUE THREAD

**Issue by a1cooke** [jongyoul/gradle-slack-plugin#8]
When creating an block element of type actions, it is not currently possible to create a button that is associated to a `url`.

This is described here: https://api.slack.com/reference/block-kit/block-elements

**Comment by jongyoul** [comment]
I've merged it. I'll deploy it by today. :-) Thank for taking care or it!!

**Comment by jongyoul** [comment]
Released 0.0.23 now. Thank you.
